version: "3.8"

services:
  db:
    image: postgres
    container_name: rollsync-auth-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - integrations.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rollsync-auth-netword

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    container_name: rollsync-auth-pgadmin
    restart: always
    ports:
      - "8888:80"
    env_file:
      - integrations.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - rollsync-auth-netword
  
  api:
    container_name: rollsync-auth-service-img
    image: rollsync-auth-service
    depends_on:
      - db
    build: 
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
      - "9229:9229"
    networks:
    - rollsync-auth-netword

volumes:
  db_data:
  pgadmin_data:
    driver: local

networks:
  rollsync-auth-netword:
    driver: bridge
