FROM node:18-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY ["package.json","pnpm-lock.yaml", "nest-cli.json","biome.json", "./"]

RUN pnpm install

COPY ["src","./src"]

COPY ["tsconfig.json","tsconfig.build.json","./"]

EXPOSE 5000
EXPOSE 9229

CMD [ "pnpm","run","start:debug"]